
import java.awt.Color;
import model.Mesa;
import model.Item;
import model.RestauranteModel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Atendimento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author carlos_vinicios
 */
public class controleMesa extends javax.swing.JDialog {

    private DefaultListModel itensModel;
    private ArrayList<Item> itens;
    private Mesa mesa;
    private RestauranteModel restaurante;
    private Restaurante mainGui;
    private int index;
    /**
     * Creates new form controleMesa
     */
    public controleMesa(RestauranteModel restaurante, Restaurante r, Mesa mesa, int index) {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo( null );
        this.getContentPane().setBackground(new Color(205, 179, 159));
        this.mesa = mesa;
        this.restaurante = restaurante;
        this.index = index;
        this.mainGui = r;
        alterValues();
    }

    private void alterValues() {
        feedItensList();
        if (this.itens.size() > 0) {
            this.totalLabel.setText("Total: R$" + String.format("%.2f", this.mesa.totalConta()));
            this.totalPessoaLabel.setText("Total p/ pessoa: R$" + String.format("%.2f", this.mesa.totalContaPorCliente()));
            this.gorjetaLabel.setText("Gorjeta: R$" + String.format("%.2f", this.mesa.calcGorjeta()));
        }
    }

    private void feedItensList() {
        String text = "";
        this.itensModel = new DefaultListModel();
        this.itensjList.setModel(itensModel);
        this.itens = this.mesa.getPedidos();
        System.out.print(this.mesa.getPedidos().size());
        for (int i = 0; i < this.mesa.getPedidos().size(); i++) {
            text = this.mesa.getPedidos().get(i).getCod() + " - R$ " + this.mesa.getPedidos().get(i).getPreco() + " - Qtd: " + this.mesa.getPedidos().get(i).getQtd();
            itensModel.addElement(text);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensjList = new javax.swing.JList<>();
        totalLabel = new javax.swing.JLabel();
        totalPessoaLabel = new javax.swing.JLabel();
        gorjetaLabel = new javax.swing.JLabel();
        fecharContajButton = new javax.swing.JButton();
        voltarjButton = new javax.swing.JButton();
        removerItemjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Mesa");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de Mesa");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel2.setText("Itens pedidos:");

        itensjList.setBackground(new java.awt.Color(234, 221, 212));
        itensjList.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        itensjList.setSelectionBackground(new java.awt.Color(33, 12, 18));
        jScrollPane1.setViewportView(itensjList);

        totalLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        totalLabel.setText("Total");

        totalPessoaLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        totalPessoaLabel.setText("Total p/ pessoa:");

        gorjetaLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        gorjetaLabel.setText("Gorjeta");

        fecharContajButton.setBackground(new java.awt.Color(33, 12, 18));
        fecharContajButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        fecharContajButton.setForeground(new java.awt.Color(255, 255, 255));
        fecharContajButton.setText("Fechar Conta");
        fecharContajButton.setMaximumSize(new java.awt.Dimension(110, 41));
        fecharContajButton.setMinimumSize(new java.awt.Dimension(110, 41));
        fecharContajButton.setPreferredSize(new java.awt.Dimension(110, 41));
        fecharContajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharContajButtonActionPerformed(evt);
            }
        });

        voltarjButton.setBackground(new java.awt.Color(33, 12, 18));
        voltarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        voltarjButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarjButton.setText("Voltar");
        voltarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarjButtonActionPerformed(evt);
            }
        });

        removerItemjButton.setBackground(new java.awt.Color(33, 12, 18));
        removerItemjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        removerItemjButton.setForeground(new java.awt.Color(255, 255, 255));
        removerItemjButton.setText("Remover");
        removerItemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerItemjButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gorjetaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPessoaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voltarjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecharContajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerItemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addComponent(totalPessoaLabel)
                .addGap(18, 18, 18)
                .addComponent(gorjetaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharContajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharContajButtonActionPerformed
        String resp = JOptionPane.showInputDialog(null, "Quanto gostou do atendimento:\n1-Péssimo\n2-Ruim\n3-Médio\n4-Bom\n5-Muito Bom", "Avaliação", -1);
        Atendimento atendimento;
        if (resp != null && !"".equals(resp)) {
            atendimento = this.mesa.fecharConta(this.restaurante, Integer.parseInt(resp));
            this.restaurante.gerarCupon(atendimento);
            this.restaurante.gravarAtendimentos();
            this.restaurante.gravarGarcons();
            this.mainGui.liberarMesa(this.index);
            this.dispose();
        }
    }//GEN-LAST:event_fecharContajButtonActionPerformed

    private void voltarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarjButtonActionPerformed

    private void removerItemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemjButtonActionPerformed
        if (this.itensjList.getSelectedIndex() != -1) {
            this.mesa.removeItem(this.itens.get(this.itensjList.getSelectedIndex()).getCod(), 1);
        }
        alterValues();
    }//GEN-LAST:event_removerItemjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharContajButton;
    private javax.swing.JLabel gorjetaLabel;
    private javax.swing.JList<String> itensjList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerItemjButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalPessoaLabel;
    private javax.swing.JButton voltarjButton;
    // End of variables declaration//GEN-END:variables
}
