
import model.Mesa;
import model.Item;
import model.RestauranteModel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author carlos_vinicios
 */
public class controleMesa extends javax.swing.JFrame {

    private DefaultListModel itensModel;
    private ArrayList<Item> itens;
    private Mesa mesa;
    private RestauranteModel restaurante;
    private Restaurante mainGui;
    private int index;
    /**
     * Creates new form controleMesa
     */
    public controleMesa(RestauranteModel restaurante, Restaurante r, Mesa mesa, int index) {
        initComponents();
        setLocationRelativeTo( null );
        this.mesa = mesa;
        this.restaurante = restaurante;
        this.index = index;
        this.mainGui = r;
        alterValues();
    }

    private void alterValues() {
        feedItensList();
        if (this.itens.size() > 0) {
            this.totalLabel.setText("Total: R$" + String.format("%.2f", this.mesa.totalConta()));
            this.totalPessoaLabel.setText("Total p/ pessoa: R$" + String.format("%.2f", this.mesa.totalContaPorCliente()));
            this.gorjetaLabel.setText("Gorjeta: R$" + String.format("%.2f", this.mesa.calcGorjeta()));
        }
    }

    private void feedItensList() {
        String text = "";
        this.itensModel = new DefaultListModel();
        this.itensjList.setModel(itensModel);
        this.itens = this.mesa.getPedidos();
        System.out.print(this.mesa.getPedidos().size());
        for (int i = 0; i < this.mesa.getPedidos().size(); i++) {
            text = this.mesa.getPedidos().get(i).getCod() + " - R$ " + this.mesa.getPedidos().get(i).getPreco() + " - Qtd: " + this.mesa.getPedidos().get(i).getQtd();
            itensModel.addElement(text);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensjList = new javax.swing.JList<>();
        totalLabel = new javax.swing.JLabel();
        totalPessoaLabel = new javax.swing.JLabel();
        gorjetaLabel = new javax.swing.JLabel();
        fecharContajButton = new javax.swing.JButton();
        voltarjButton = new javax.swing.JButton();
        removerItemjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Mesa");
        setResizable(false);

        jLabel1.setText("Controle de Mesa");

        jLabel2.setText("Itens pedidos:");

        jScrollPane1.setViewportView(itensjList);

        totalLabel.setText("Total");

        totalPessoaLabel.setText("Total p/ pessoa:");

        gorjetaLabel.setText("Gorjeta");

        fecharContajButton.setText("Fechar Conta");
        fecharContajButton.setMaximumSize(new java.awt.Dimension(110, 41));
        fecharContajButton.setMinimumSize(new java.awt.Dimension(110, 41));
        fecharContajButton.setPreferredSize(new java.awt.Dimension(110, 41));
        fecharContajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharContajButtonActionPerformed(evt);
            }
        });

        voltarjButton.setText("Voltar");
        voltarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarjButtonActionPerformed(evt);
            }
        });

        removerItemjButton.setText("Remover");
        removerItemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 361, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gorjetaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPessoaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(voltarjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fecharContajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removerItemjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerItemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addComponent(totalPessoaLabel)
                .addGap(18, 18, 18)
                .addComponent(gorjetaLabel)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharContajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharContajButtonActionPerformed
        String resp = JOptionPane.showInputDialog(null, "Quanto gostou do atendimento:\n1-Péssimo\n2-Ruim\n3-Médio\n4-Bom\n5-Muito Bom", "Avaliação", -1);
        if (resp != null && !"".equals(resp)) {
            this.mesa.fecharConta(this.restaurante, Integer.parseInt(resp));
            this.restaurante.gerarCupon(this.mesa);
            this.restaurante.gravarAtendimentos();
            this.restaurante.gravarGarcons();
            this.mainGui.liberarMesa(this.index);
            this.dispose();
        }
    }//GEN-LAST:event_fecharContajButtonActionPerformed

    private void voltarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarjButtonActionPerformed

    private void removerItemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemjButtonActionPerformed
        if (this.itensjList.getSelectedIndex() != -1) {
            this.mesa.removeItem(this.itens.get(this.itensjList.getSelectedIndex()).getCod(), 1);
        }
        alterValues();
    }//GEN-LAST:event_removerItemjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharContajButton;
    private javax.swing.JLabel gorjetaLabel;
    private javax.swing.JList<String> itensjList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerItemjButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalPessoaLabel;
    private javax.swing.JButton voltarjButton;
    // End of variables declaration//GEN-END:variables
}
