import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Cardapio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos_vinicios
 */
public class itensPedidos extends javax.swing.JFrame {
    private DefaultListModel itensModel;
    private NewPedido fatherGUI;
    private ArrayList<Cardapio> itensSelecionados;
    private ArrayList qtds;
    
    /**
     * Creates new form itensPedidos
     */
    public itensPedidos(NewPedido father) {
        initComponents();
        setLocationRelativeTo( null );
        this.fatherGUI = father;
        feedListItens();
    }
    
    private void feedListItens(){
        String text;
        this.itensSelecionados = this.fatherGUI.getSelecionados();
        this.qtds = this.fatherGUI.getQtds();
        this.itensModel = new DefaultListModel();
        this.itensjList.setModel(this.itensModel);
        for(int i=0; i < this.itensSelecionados.size(); i++){
            text = this.itensSelecionados.get(i).getCod() + " - " + this.itensSelecionados.get(i).getDecricao() + " - " + this.itensSelecionados.get(i).getPreco() + " - Qtd: " + this.qtds.get(i);
            itensModel.addElement(text);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensjList = new javax.swing.JList<>();
        removerjButton = new javax.swing.JButton();
        fecharjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Itens selecionados");
        setLocation(new java.awt.Point(0, 0));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Itens selecionados");

        itensjList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(itensjList);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        fecharjButton.setText("Fechar");
        fecharjButton.setMaximumSize(new java.awt.Dimension(85, 40));
        fecharjButton.setMinimumSize(new java.awt.Dimension(85, 40));
        fecharjButton.setPreferredSize(new java.awt.Dimension(85, 40));
        fecharjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removerjButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(fecharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(fecharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
       if (this.itensjList.getSelectedIndex() != -1) {
            this.fatherGUI.alterItens(this.itensjList.getSelectedIndex());
        }
        feedListItens();
    }//GEN-LAST:event_removerjButtonActionPerformed

    private void fecharjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharjButton;
    private javax.swing.JList<String> itensjList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerjButton;
    // End of variables declaration//GEN-END:variables
}
