import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import model.RestauranteModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos_vinicios
 */
public class NewControlePedidos extends javax.swing.JDialog {
    private DefaultListModel pedidosModel;
    private RestauranteModel restaurante;
    
    /**
     * Creates new form NewControlePedidos
     */
    public NewControlePedidos(RestauranteModel restaurante) {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo( null );
        this.getContentPane().setBackground(new Color(205, 179, 159));
        this.restaurante = restaurante;
        feedPedidoList();
    }
    
    private void feedPedidoList(){
        this.pedidosModel = new DefaultListModel();
        this.pedidosjList.setModel(pedidosModel);
        //busca os pedidos ativos no dia
        pedidosModel.addElement("Testeeeee");
        pedidosModel.addElement("Testeeeee");
        pedidosModel.addElement("Testeeeee");
    }
    
    private ArrayList selecaoParam(String textBusca){
        int i;
        ArrayList busca = new ArrayList(); //cria um array para armazenar o resultado da busca
        for(i=0; i < pedidosModel.size(); i++){ //realiza a busca dentro do model
            String item = (String) this.pedidosModel.get(i);
            if(item.contains(textBusca)){
                busca.add(i);
            }
        }
        return busca;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel = new javax.swing.JLabel();
        buscarText = new javax.swing.JTextField();
        buscarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosjList = new javax.swing.JList<>();
        selecionarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de pedidos");
        setResizable(false);

        titlejLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        titlejLabel.setText("Selecione o pedido");

        buscarText.setBackground(new java.awt.Color(234, 221, 212));
        buscarText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        buscarjButton.setBackground(new java.awt.Color(33, 12, 18));
        buscarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        buscarjButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarjButton.setText("Buscar");
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });

        pedidosjList.setBackground(new java.awt.Color(234, 221, 212));
        pedidosjList.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        pedidosjList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pedidosjList.setSelectionBackground(new java.awt.Color(33, 12, 18));
        pedidosjList.setVisibleRowCount(15);
        jScrollPane1.setViewportView(pedidosjList);

        selecionarjButton.setBackground(new java.awt.Color(33, 12, 18));
        selecionarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        selecionarjButton.setForeground(new java.awt.Color(255, 255, 255));
        selecionarjButton.setText("Selecionar");
        selecionarjButton.setMaximumSize(new java.awt.Dimension(110, 29));
        selecionarjButton.setMinimumSize(new java.awt.Dimension(110, 40));
        selecionarjButton.setPreferredSize(new java.awt.Dimension(110, 40));
        selecionarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setBackground(new java.awt.Color(33, 12, 18));
        cancelarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cancelarjButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setMaximumSize(new java.awt.Dimension(85, 40));
        cancelarjButton.setMinimumSize(new java.awt.Dimension(85, 40));
        cancelarjButton.setPreferredSize(new java.awt.Dimension(85, 40));
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarjButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(selecionarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(titlejLabel)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titlejLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarjButton)
                    .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        //filtra a lista com base no código ou texto dado
        String textBusca = this.buscarText.getText();
        String option;
        int i;
        ArrayList resp;
        resp = selecaoParam(textBusca);
        if( resp.size() > 1){
            String textMessage = "Foram encontrados mais de uma referência para busca, selecione e digite o código correspondente:\n";
            for(i=0; i < resp.size(); i++)
                textMessage = textMessage + pedidosModel.get((int)resp.get(i)) + "\n";
            option = JOptionPane.showInputDialog(textMessage); //cria a caixa de dialogo com os valores semelhantes encontrados
            resp = selecaoParam(option);
        }
        this.pedidosjList.setSelectedIndex((int)resp.get(0)); //seta o indice selecionado
        this.buscarText.setText(""); //limpa o campo de busca
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void selecionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarText;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> pedidosjList;
    private javax.swing.JButton selecionarjButton;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
