import java.util.ArrayList;
import java.util.Random;
import model.Garcom;
import model.RestauranteModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos_vinicios
 */
public class NewFuncionario extends javax.swing.JFrame {
    private RestauranteModel restaurante;
    private Boolean alterar = false;
    private ArrayList <Garcom> garcons;
    private int indexAlter;
    /**
     * Creates new form NewFuncionario
     */
    public NewFuncionario(RestauranteModel restaurante) {
        initComponents();
        setLocationRelativeTo( null );
        Random rand = new Random();
        int cod = 1000 + rand.nextInt(1000);
        this.codText.setText(String.valueOf(cod));
        this.restaurante = restaurante;
    }
    
    public NewFuncionario(RestauranteModel restaurante, int index){
        initComponents();
        this.restaurante = restaurante;
        this.garcons = this.restaurante.getGarcons();
        this.alterar = true;
        this.codText.setText(String.valueOf(this.garcons.get(index).getCod()));
        this.nomeText.setText(this.garcons.get(index).getNome());
        this.indexAlter = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        codText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Funcionário");
        setPreferredSize(new java.awt.Dimension(398, 234));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Cod.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(40, 25, 40, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        codText.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(40, 30, 40, 20);
        getContentPane().add(codText, gridBagConstraints);

        jLabel3.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 40, 0);
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 40, 20);
        getContentPane().add(nomeText, gridBagConstraints);

        salvarButton.setText("Salvar");
        salvarButton.setMaximumSize(new java.awt.Dimension(85, 40));
        salvarButton.setMinimumSize(new java.awt.Dimension(85, 40));
        salvarButton.setPreferredSize(new java.awt.Dimension(85, 40));
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        getContentPane().add(salvarButton, gridBagConstraints);

        cancelarButton.setText("Cancelar");
        cancelarButton.setMaximumSize(new java.awt.Dimension(85, 40));
        cancelarButton.setMinimumSize(new java.awt.Dimension(85, 40));
        cancelarButton.setPreferredSize(new java.awt.Dimension(85, 40));
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 15, 0);
        getContentPane().add(cancelarButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        String cod = this.codText.getText();
        String nome = this.nomeText.getText();
        if(!alterar){
            this.restaurante.addGarcons(Integer.parseInt(cod), nome);
        }else{
            this.garcons.get(this.indexAlter).setNome(nome);
        }
        this.restaurante.gravarGarcons();
        this.dispose();
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomeText;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
