
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import model.Atendimento;
import model.RestauranteModel;
import model.Cardapio;
import model.Mesa;
import model.Garcom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author carlos_vinicios
 */
public class NewPedido extends javax.swing.JDialog {
    private DefaultListModel cardapioModel;
    private RestauranteModel restaurante;
    private ArrayList<Cardapio> cardapio;
    private ArrayList<Cardapio> itensSelecionados;
    private ArrayList<Garcom> garcons;
    private ArrayList qtds;
    private Restaurante mainGui;

    /**
     * Creates new form NewPedido
     */
    public NewPedido(RestauranteModel restaurante, Restaurante r) {
        initComponents();
        this.setLocationRelativeTo( null );
        this.getContentPane().setBackground(new Color(205, 179, 159));
        this.setModal(true);
        this.restaurante = restaurante;
        this.cardapio = this.restaurante.getCardapio();
        this.garcons = this.restaurante.getGarcons();
        this.itensSelecionados = new ArrayList();
        this.qtds = new ArrayList();
        this.mainGui = r;
        feedCardapioList();
    }

    public NewPedido(RestauranteModel restaurante, int codMesa, int codGarcom) {
        initComponents();
        setLocationRelativeTo( null );
        this.restaurante = restaurante;
        this.codGarcomText.setText(String.valueOf(codGarcom));
        this.codMesaText.setText(String.valueOf(codMesa));
        this.cardapio = this.restaurante.getCardapio();
        this.garcons = this.restaurante.getGarcons();
        this.itensSelecionados = new ArrayList();
        this.qtds = new ArrayList();
        feedCardapioList();
    }

    private void feedCardapioList() {
        String text;
        this.cardapioModel = new DefaultListModel();
        this.cardapioList.setModel(cardapioModel);
        for (int i = 0; i < this.cardapio.size(); i++) {
            text = this.cardapio.get(i).getCod() + " - " + this.cardapio.get(i).getDecricao() + " - " + this.cardapio.get(i).getPreco();
            cardapioModel.addElement(text);
        }
    }

    private ArrayList selecaoParam(String textBusca) {
        int i;
        ArrayList busca = new ArrayList(); //cria um array para armazenar o resultado da busca
        for (i = 0; i < cardapioModel.size(); i++) { //realiza a busca dentro do model
            String item = (String) this.cardapioModel.get(i);
            if (item.contains(textBusca)) {
                busca.add(i);
            }
        }
        return busca;
    }
    
    public void alterItens(int index){
        int value = (int) this.qtds.get(index)-1;
        if(value != 0)
            this.qtds.set(index, value);
        else{
            this.qtds.remove(index);
            this.itensSelecionados.remove(index);
        }
    }
    
    public ArrayList<Cardapio> getSelecionados(){
        return this.itensSelecionados;
    }
    
    public ArrayList getQtds(){
        return this.qtds;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        garcomjLabel = new javax.swing.JLabel();
        codGarcomText = new javax.swing.JTextField();
        mesajLabel = new javax.swing.JLabel();
        codMesaText = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardapioList = new javax.swing.JList<>();
        jcardapioLabel1 = new javax.swing.JLabel();
        buscarjButton = new javax.swing.JButton();
        buscarText = new javax.swing.JTextField();
        adicionarjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        visualizarjButton = new javax.swing.JButton();
        quantidadeText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Pedido");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        garcomjLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        garcomjLabel.setText("Código Garçom");
        garcomjLabel.setToolTipText("");

        codGarcomText.setBackground(new java.awt.Color(234, 221, 212));
        codGarcomText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        codGarcomText.setToolTipText("");

        mesajLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mesajLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mesajLabel.setText("Código Mesa");
        mesajLabel.setToolTipText("");

        codMesaText.setBackground(new java.awt.Color(234, 221, 212));
        codMesaText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        savejButton.setBackground(new java.awt.Color(33, 12, 18));
        savejButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        savejButton.setForeground(new java.awt.Color(255, 255, 255));
        savejButton.setText("Salvar");
        savejButton.setMaximumSize(new java.awt.Dimension(85, 40));
        savejButton.setMinimumSize(new java.awt.Dimension(85, 40));
        savejButton.setPreferredSize(new java.awt.Dimension(85, 40));
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        canceljButton.setBackground(new java.awt.Color(33, 12, 18));
        canceljButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        canceljButton.setForeground(new java.awt.Color(255, 255, 255));
        canceljButton.setText("Cancelar");
        canceljButton.setMaximumSize(new java.awt.Dimension(85, 40));
        canceljButton.setMinimumSize(new java.awt.Dimension(85, 40));
        canceljButton.setPreferredSize(new java.awt.Dimension(85, 40));
        canceljButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canceljButtonMouseClicked(evt);
            }
        });

        cardapioList.setBackground(new java.awt.Color(234, 221, 212));
        cardapioList.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        cardapioList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cardapioList.setSelectionBackground(new java.awt.Color(33, 12, 18));
        jScrollPane1.setViewportView(cardapioList);

        jcardapioLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jcardapioLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcardapioLabel1.setText("Cardápio");

        buscarjButton.setBackground(new java.awt.Color(33, 12, 18));
        buscarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        buscarjButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarjButton.setText("Buscar");
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });

        buscarText.setBackground(new java.awt.Color(234, 221, 212));
        buscarText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        adicionarjButton.setBackground(new java.awt.Color(33, 12, 18));
        adicionarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        adicionarjButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarjButton.setText("Adicionar");
        adicionarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarjButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade");

        visualizarjButton.setBackground(new java.awt.Color(33, 12, 18));
        visualizarjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        visualizarjButton.setForeground(new java.awt.Color(255, 255, 255));
        visualizarjButton.setText("Visualizar");
        visualizarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarjButtonActionPerformed(evt);
            }
        });

        quantidadeText.setBackground(new java.awt.Color(234, 221, 212));
        quantidadeText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcardapioLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garcomjLabel)
                            .addComponent(mesajLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codMesaText)
                            .addComponent(codGarcomText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarjButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adicionarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visualizarjButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(garcomjLabel)
                    .addComponent(codGarcomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesajLabel)
                    .addComponent(codMesaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcardapioLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarjButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarjButton)
                    .addComponent(jLabel3)
                    .addComponent(visualizarjButton)
                    .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        int i, codMesa;
        String label = "Deseja adicionar os seguintes intens?\n";
        Mesa mesa = null;
        Garcom garcom = null;
        Atendimento atendimento = null;
        ArrayList<Mesa> mesas = this.restaurante.getMesas();
        if (this.itensSelecionados.size() > 0) {
            for (i = 0; i < this.itensSelecionados.size(); i++) {
                label = label + this.itensSelecionados.get(i).getCod() + " - " + this.itensSelecionados.get(i).getDecricao() + " - " + this.itensSelecionados.get(i).getPreco() + " - qtd: " + this.qtds.get(i) + "\n";
            }
            if (JOptionPane.showConfirmDialog(null, label, "Adicionar itens",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (!"".equals(this.codMesaText.getText())) {
                    codMesa = Integer.parseInt(this.codMesaText.getText());
                    for (i = 0; i < mesas.size(); i++) {
                        if (mesas.get(i).getCod() == codMesa) {
                            mesa = mesas.get(i);
                            break;
                        }
                    }
                    if (mesa != null) {
                        for (i = 0; i < this.itensSelecionados.size(); i++) {
                            mesa.addItem(this.cardapio, this.itensSelecionados.get(i).getCod(), (int) this.qtds.get(i));
                        }
                    }
                } else {
                    String codGarcom = this.codGarcomText.getText();
                    if (!"".equals(codGarcom)) {
                        for (i = 0; i < this.garcons.size(); i++) {
                            if (this.garcons.get(i).getCod() == Integer.parseInt(codGarcom)) {
                                garcom = this.garcons.get(i);
                                break;
                            }
                        }
                        mesa = new Mesa(1, true, garcom, 100);
                        for (i = 0; i < this.itensSelecionados.size(); i++) {
                            mesa.addItem(this.cardapio, this.itensSelecionados.get(i).getCod(), (int) this.qtds.get(i));
                        }
                        String resp = JOptionPane.showInputDialog(null, "Quanto gostou do atendimento:\n1-Péssimo\n2-Ruim\n3-Médio\n4-Bom\n5-Muito Bom", "Avaliação", -1);
                        if (resp != null && !"".equals(resp)) {
                            atendimento = mesa.fecharConta(this.restaurante, Integer.parseInt(resp));
                            this.restaurante.gerarCupon(atendimento);
                            this.restaurante.gravarAtendimentos();
                            this.restaurante.gravarGarcons();
                            this.mainGui.setTotalCaixa();
                            this.dispose();
                        }
                    }
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void canceljButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canceljButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_canceljButtonMouseClicked

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        //filtra a lista com base no código ou texto dado
        String textBusca = this.buscarText.getText();
        String option;
        int i;
        ArrayList resp;
        resp = selecaoParam(textBusca);
        if (resp.size() > 1) {
            String textMessage = "Foram encontrados mais de uma referência para busca, selecione e digite o código correspondente:\n";
            for (i = 0; i < resp.size(); i++) {
                textMessage = textMessage + cardapioModel.get((int) resp.get(i)) + "\n";
            }
            option = JOptionPane.showInputDialog(null, textMessage, "Opções", -1); //cria a caixa de dialogo com os valores semelhantes encontrados
            resp = selecaoParam(option);
        }
        this.cardapioList.setSelectedIndex((int) resp.get(0)); //seta o indice selecionado
        this.buscarText.setText(""); //limpa o campo de busca
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void adicionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarjButtonActionPerformed
        String qtd_str = this.quantidadeText.getText();
        if(qtd_str != "" && qtd_str != null){
            int qtd = Integer.parseInt(qtd_str);
            if(qtd > 0){
                this.itensSelecionados.add(this.cardapio.get(this.cardapioList.getSelectedIndex()));
                this.qtds.add(qtd);
            }
        }
        this.quantidadeText.setText("");
        this.cardapioList.setSelectedIndex(-1);
    }//GEN-LAST:event_adicionarjButtonActionPerformed

    private void visualizarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarjButtonActionPerformed
           new itensPedidos(this).setVisible(true);
    }//GEN-LAST:event_visualizarjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarjButton;
    private javax.swing.JTextField buscarText;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JList<String> cardapioList;
    private javax.swing.JTextField codGarcomText;
    private javax.swing.JTextField codMesaText;
    private javax.swing.JLabel garcomjLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcardapioLabel1;
    private javax.swing.JLabel mesajLabel;
    private javax.swing.JTextField quantidadeText;
    private javax.swing.JButton savejButton;
    private javax.swing.JButton visualizarjButton;
    // End of variables declaration//GEN-END:variables
}
