import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import model.RestauranteModel;
import model.Atendimento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos_vinicios
 */
public class TotalDia extends javax.swing.JFrame {
    private DefaultListModel atendimentosModel;
    private RestauranteModel restaurante;
    private ArrayList<Atendimento> atendimentos;
    private float total = 0;
    /**
     * Creates new form TotalDia
     */
    public TotalDia(RestauranteModel restaurante) {
        initComponents();
        setLocationRelativeTo( null );
        this.restaurante = restaurante;
        this.atendimentos = this.restaurante.getAtendimento();
        feedListAtendimento();
        this.totaljLabel.setText("Total: R$ " + String.format("%.2f", this.total));
    }
    
    private void feedListAtendimento(){
        this.atendimentosModel = new DefaultListModel();
        this.atendimentosjList.setModel(this.atendimentosModel);
        for(int i = 0; i < this.atendimentos.size(); i++){
            atendimentosModel.addElement(this.atendimentos.get(i).getTotal());
            this.total+=this.atendimentos.get(i).getTotal();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atendimentosjList = new javax.swing.JList<>();
        totaljLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas do dia");
        setResizable(false);

        jLabel1.setText("Vendas do Dia");

        atendimentosjList.setVisibleRowCount(20);
        jScrollPane1.setViewportView(atendimentosjList);

        totaljLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totaljLabel.setText("Total: R$");

        jButton1.setText("Confirmar");
        jButton1.setMaximumSize(new java.awt.Dimension(95, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(95, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(95, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(totaljLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(totaljLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> atendimentosjList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totaljLabel;
    // End of variables declaration//GEN-END:variables
}
