
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos_vinicios
 */
public class totalDiaGarcom extends javax.swing.JDialog {

    /**
     * Creates new form totalDiaGarcom
     */
    public totalDiaGarcom(double total) {
        initComponents();
        this.setLocationRelativeTo( null );
        this.getContentPane().setBackground(new Color(205, 179, 159));
        this.setModal(true);
        this.totalLabel.setText("Total do dia: R$" + String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalLabel = new javax.swing.JLabel();
        fecharjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Total garçom");
        setModalityType(null);
        setType(java.awt.Window.Type.POPUP);

        totalLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("Total: R$");

        fecharjButton.setBackground(new java.awt.Color(33, 12, 18));
        fecharjButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        fecharjButton.setForeground(new java.awt.Color(255, 255, 255));
        fecharjButton.setText("Fechar");
        fecharjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(fecharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(fecharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharjButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
